/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.CourseOnline;

/**
 *
 * @author Admin
 */
public class OnlineCourse extends javax.swing.JPanel {

    /**
     * Creates new form OnlineCourse
     */
    public OnlineCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTeacher = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCourseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtTitle = new javax.swing.JTextField();
        jtxtCredit = new javax.swing.JTextField();
        jtxtLocation = new javax.swing.JTextField();
        jcomboDepartment = new javax.swing.JComboBox<>();
        jbtAdd = new javax.swing.JButton();
        jbtedit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtdelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(950, 513));

        tbTeacher.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tbTeacher.setForeground(new java.awt.Color(102, 102, 102));
        tbTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TeacherID", "Last Name", "First Name", "Hire Date"
            }
        ));
        tbTeacher.setToolTipText("");
        tbTeacher.setRowHeight(30);
        tbTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTeacher);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("CourseID");

        jtxtCourseID.setEditable(false);

        jLabel3.setText("Title");

        jLabel4.setText("Credits");

        jLabel5.setText("Department Name");

        jLabel6.setText("Url");

        jcomboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/add.png"))); // NOI18N
        jbtAdd.setText("ADD");
        jbtAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtAddMouseClicked(evt);
            }
        });

        jbtedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/pencil.png"))); // NOI18N
        jbtedit.setText("EDIT");
        jbtedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbteditMouseClicked(evt);
            }
        });
        jbtedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbteditActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/reset.png"))); // NOI18N
        jButton4.setText("RESET");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jbtdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/icon/delete (2).png"))); // NOI18N
        jbtdelete.setText("DELETE");
        jbtdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtdeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtLocation)
                                    .addComponent(jcomboDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtTitle)
                                    .addComponent(jtxtCredit)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtedit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtedit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 161, 255));
        jLabel1.setText("ONLINE COURSE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTeacherMouseClicked
        int i = tbTeacher.getSelectedRow();
        if (i >= 0) {
            txtTeacherID.setText(model.getValueAt(i, 0).toString());
            txtLastName.setText(model.getValueAt(i, 1).toString());
            txtFirstName.setText(model.getValueAt(i, 2).toString());
            txtHireDate.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_tbTeacherMouseClicked

    private void jbteditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbteditMouseClicked
        if(jtxtTitle.getText().isEmpty()||jtxtCredit.getText().isEmpty()||jcomboDepartment.getSelectedItem().equals(null)||jtxtLocation.getText().isEmpty()||jtxtDay.getText().isEmpty()||jtxtTime.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Edit Data Invalid");
            return;
        }
        int id=Integer.parseInt(jtxtCourseID.getText());
        String Location=jtxtLocation.getText();
        String Day=jtxtDay.getText();
        String Time=jtxtTime.getText();
        String Title=jtxtTitle.getText();
        if(!jtxtCredit.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(null, "Credit must be number");
            return;
        }
        int Credit=Integer.parseInt(jtxtCredit.getText());
        int Department=Integer.parseInt(jcomboDepartment.getSelectedItem().toString()) ;
        int input=JOptionPane.showConfirmDialog(null,"Are you sure edit this course", "Confirm Edit", JOptionPane.YES_NO_OPTION);
        if(input==JOptionPane.YES_OPTION){
            if(courseBLL.editCourseBLL(id, Title, Credit, Department)&&onsiteCourseBLL.editOnsiteCourseBLL(id, Location, Day, Time)){
                JOptionPane.showMessageDialog(null, "Edit Successful");
                displayDatatoTable();
                displayDatatoComboBox();
            }else{
                JOptionPane.showConfirmDialog(null, "Edit Data Failed");
            }
        }

    }//GEN-LAST:event_jbteditMouseClicked

    private void jbteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbteditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbteditActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        onsiteCourseBLL.reset(jtxtCourseID, jtxtTitle, jtxtCredit, jcomboDepartment, jtxtLocation, jtxtDay, jtxtTime);
        //        jcomboDepartment.setSelectedIndex(-1);
        //       jtxtCourseID.setText("");
        //       jtxtTitle.setText("");
        //       jtxtCredit.setText("");
        //       jtxtLocation.setText("");
        //       jtxtDay.setText("");
        //       jtxtTime.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jbtdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtdeleteMouseClicked

        System.out.println("kết quả"+jtxtCourseID.getText().isEmpty());
        if(jtxtCourseID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please select course to delete");
            return ;
        }
        int id=Integer.parseInt(jtxtCourseID.getText().toString());
        if(onsiteCourseBLL.courseIDcheckDelete(id)){
            int input=JOptionPane.showConfirmDialog(null, "Are you sure delete this course","Confirm Delete", JOptionPane.YES_NO_OPTION);
            if(input==JOptionPane.YES_OPTION){
                if(onsiteCourseBLL.deleteonsiteCourse(id)&&courseBLL.deletecoursonsite(id)){
                    JOptionPane.showMessageDialog(null, "Delete Successful!");
                }else{
                    JOptionPane.showMessageDialog(null, "Delete Failed!");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Can't Delete This Course");
        }
        displayDatatoTable();
        onsiteCourseBLL.reset(jtxtCourseID, jtxtTitle, jtxtCredit, jcomboDepartment, jtxtLocation, jtxtDay, jtxtTime);

    }//GEN-LAST:event_jbtdeleteMouseClicked

    private void jbtAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtAddMouseClicked
        if(jtxtTitle.getText().isEmpty()||jtxtCredit.getText().isEmpty()||jtxtCredit.getText().isEmpty()||jcomboDepartment.getSelectedItem().equals(null)|
            jtxtLocation.getText().isEmpty()||jtxtDay.getText().isEmpty()||jtxtTime.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Add Data Invalid");
            return ;
        }
        else if(jtxtCourseID.getText().equals(model.getValueAt(row, 0).toString())){
            JOptionPane.showMessageDialog(null, "Onsite Course exist");
            return;
        }
        else{
            if(!jtxtCredit.getText().matches("\\d+")){
                JOptionPane.showMessageDialog(null, "Credit must be number");
                return;
            }
            int input=JOptionPane.showConfirmDialog(null, "Are you sure Add data?","Add Data", JOptionPane.YES_NO_OPTION);
            if(input==JOptionPane.YES_OPTION){

                String Title=jtxtTitle.getText();

                int credit=Integer.parseInt(jtxtCredit.getText());

                int department=Integer.parseInt(jcomboDepartment.getSelectedItem().toString());
                String location=jtxtLocation.getText();
                String Day=jtxtDay.getText();
                String Time=jtxtTime.getText();

                if(courseBLL.addCourseBLL( Title, credit, department)){
                    int id=courseBLL.getCourseID();
                    if(onsiteCourseBLL.addOnsiteCourseBLL(id, location, Day, Time)){
                        JOptionPane.showMessageDialog(null, "Add Data Successful");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Add Data Failed");
                }
            }

        }
        displayDatatoTable();
        onsiteCourseBLL.reset(jtxtCourseID, jtxtTitle, jtxtCredit, jcomboDepartment, jtxtLocation, jtxtDay, jtxtTime);
    }//GEN-LAST:event_jbtAddMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtdelete;
    private javax.swing.JButton jbtedit;
    private javax.swing.JComboBox<String> jcomboDepartment;
    private javax.swing.JTextField jtxtCourseID;
    private javax.swing.JTextField jtxtCredit;
    private javax.swing.JTextField jtxtLocation;
    private javax.swing.JTextField jtxtTitle;
    private javax.swing.JTable tbTeacher;
    // End of variables declaration//GEN-END:variables
}
