/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Course;

import BLL.Course.OnsiteCourseBLL;
import java.awt.BorderLayout;
import java.nio.channels.Channels;
import java.util.ArrayList;
import javax.swing.JFrame;
import org.ietf.jgss.Oid;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author hp_pc
 */
public class thongKeCourse extends javax.swing.JFrame {

    /**
     * Creates new form thongKeCourse
     */
       OnsiteCourseBLL onsiteBLL=new OnsiteCourseBLL();
    public thongKeCourse() {
        initComponents();
        createPieChart();
         
         
    }
  
    public  void createPieChart(){
        DefaultPieDataset dataset=new DefaultPieDataset();
        int total=onsiteBLL.getCourse().size();
        int amountOnsite=onsiteBLL.readOnsiteCourse().size();
        int amountOnline=total-amountOnsite;
        dataset.setValue("Onsite", (amountOnsite*100)/total);
        dataset.setValue("Online", (amountOnline*100)/total);
        JFreeChart chart=ChartFactory.createPieChart("THỐNG KÊ KHÓA HỌC", dataset, true, true, true);
        ChartPanel chartPanel=new ChartPanel(chart);
        JPanelChart.setLayout(new BorderLayout());
        JPanelChart.add(chartPanel,BorderLayout.CENTER);
        JPanelChart.validate();
    }
    public void createBarChart(){
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        ArrayList<Integer> idlist=onsiteBLL.listIDCourse();
        for(int id:idlist){
            dataset.addValue(onsiteBLL.getAmountStudent(id),"Số Học Sinh", onsiteBLL.getCourseByID(id).getTitle());
    }
       JFreeChart chart = ChartFactory.createBarChart(
                 "THỐNG KÊ HỌC SINH TỪNG KHÓA HỌC",
               "Môn Học" ,
                "Số Học Sinh", 
                dataset, PlotOrientation.VERTICAL,
                true,true, true
        );
        ChartPanel chartPanel=new ChartPanel(chart);
         JPanelChart.setLayout(new BorderLayout());
        JPanelChart.add(chartPanel,BorderLayout.CENTER);
        JPanelChart.validate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelChart = new javax.swing.JPanel();
        jcomboSelection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPanelChartLayout = new javax.swing.GroupLayout(JPanelChart);
        JPanelChart.setLayout(JPanelChartLayout);
        JPanelChartLayout.setHorizontalGroup(
            JPanelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanelChartLayout.setVerticalGroup(
            JPanelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jcomboSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course statistics", "Student statistics" }));
        jcomboSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPanelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 608, Short.MAX_VALUE)
                        .addComponent(jcomboSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jcomboSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(JPanelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboSelectionActionPerformed
        if(jcomboSelection.getSelectedIndex()==0){
            JPanelChart.removeAll();
            createPieChart();
        }else{
            JPanelChart.removeAll();
            createBarChart();
        }
    }//GEN-LAST:event_jcomboSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
////         thongKeCourse tk=new thongKeCourse();
////           tk.createBarChart();
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new thongKeCourse().setVisible(true);
//            }
//        });
//    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelChart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcomboSelection;
    // End of variables declaration//GEN-END:variables
}

